-dontoptimize
-dontwarn org.bukkit.**
-dontwarn net.minecraft.**
-dontwarn com.mojang.**
-dontwarn org.spigotmc.**
-dontwarn org.junit.**
-dontwarn org.mockito.**
-keep public class com.neomechanical.neomoderation.NeoModerationPlugin {
    public *;
}
-keep class com.neomechanical.neomoderation.NeoModerationPlugin
-keep class com.neomechanical.neomoderation.lib.bstats.** { *; }
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
-keepattributes RuntimeVisibleAnnotations,RuntimeInvisibleAnnotations,Signature,InnerClasses,EnclosingMethod
